spring:
  cloud:
    gateway:
      routes:
        - id: ui-redirect
          uri: no://op
          predicates:
            - Path=/ui, false
          filters:
            - RedirectTo=302, /ui/
          order: 0
        - id: ui
          uri: ${UI_SCHEME:http}://${UI_ROUTE:localhost:4200}
          predicates:
            - Path=/ui/**
          filters:
            - StripPrefix=1
          order: 1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
